### PR TITLE
Contributing and conduct

### PR DESCRIPTION
**Pull request by betatim**
Some fairly standard information on conduct and how to contribute.

Straight forward:
* every collaborator can merge PRs
* all changes are proposed by forking the repository and then making a PR
* no one can merge their own work
* use common sense, and
* be nice to everyone

We should get along swimmingly!

### CODE REVIEW

**Comment by khinsen** [comment]
Does it make sense to add this now? The proposal is submitted, so this repository should not evolve much from now on. We should start another one for the real work.

**Comment by cranmer** [comment]
Hi,

We could make a release, perhaps push to zenodo the version that was submitted, and still use this repository for further discussions.

Kyle

**Comment by ctb** [comment]
RIO has offered to publish open science prize proposals --

https://twitter.com/RIOJournal/status/703141211612155904

How about doing that?

**Comment by cranmer** [comment]
Fine with me. A release seems to make sense independently

**Comment by khinsen** [comment]
@ctb +1

@cranmer +1 as well, though it will take me some time to get used to the term "release" for a piece of prose that moreover is not supposed to evolve. I'd call it an archival copy, but the result is the same.

But the real question concerning this PR is if we continue to use it as a place for discussion.

**Comment by lukasheinrich** [comment]
:+1: for both release w/ zenodo and publishing in RIO (if it's not too involved)

**Comment by khinsen** [comment]
:+1:

**Pull request merged**
