### PR TITLE
logos: added png and svg logos

### PR DESCRIPTION
**Pull request by eamonnmag**
Signed-off-by: Eamonn Maguire <eamonnmag@gmail.com>

### CODE REVIEW

**Comment by betatim** [comment]
wut? This signed off thing is new to me. How/why do you do it? I mean, I always assumed that Eamonn agreed with what @eamonnmag was doing on gh? :confused:

**Comment by cranmer** [comment]
can we add a logo to the readme ?

**Comment by eamonnmag** [comment]
Ah, it's SOP in commits in invenio for example. It started off as a thing for getting commits in to the linux kernel and is now part of standard commit messages in many projects.

**Comment by eamonnmag** [comment]
I added it :)

**Comment by betatim** [comment]
That is quite huge. Can we shrink it? Then merge.

**Comment by eamonnmag** [comment]
Done.

**Comment by betatim** [comment]
Thanks! How much more ugly do I have to make the UI mockup before you spring to action again :sunglasses: ?

**Pull request merged**
